#!/bin/bash
# Description
#   Build the DevOpsDreamUpdater using locally installed repos. (alternate first step)
#   Use this if you are developing achel of DevOpsDream.
#   You don't need to use this if you are simply developing your own repo to work with DevOpsDream because that will already be local.
#
# Syntax:
#   $0 [repoName]
#     repoName is the repository name that can be obtained with manageAchel repoList. See dodUpdaterAddRepo.
#
# Examples:
#   Build the DevOpsDreamUpdater
#   $0
#   
#   Build the DevOpsDreamUpdater and add repo extraRepo as iss dodUpdaterAddRepo had been called. This is purely for convenience.
#   $0 extraRepo



requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh

. $libDir/dodUpdater.sh

# Do the build.
dodClientBuildLocal

# Add a repo if we've been given one.
if [ "$1" != '' ]; then
	dodAddRepo $1 client
fi
