#!/bin/bash
# Description
#   Run the DevOpsDreamUpdater. (final step)
#
# Syntax:
#   $0
#
# Examples:
#   Run the DevOpsDreamUpdater
#   $0

requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh

. $libDir/dodUpdater.sh

dodRun
