#!/bin/bash
# Description
#   Clean out all the old DevOpsDreamUpdater containers/images. Useful if you want to re-build with the latest copies of every repository.
#
# Syntax:
#   $0
#
# Examples:
#   Run the DevOpsDreamUpdater
#   $0

requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh

. $libDir/dodUpdater.sh

dodClean
