#!/bin/bash
# Description
#   Build the DevOpsDreamUpdater. (first step)
#
# Syntax:
#   $0 [repoName]
#     repoName is the repository name that can be obtained with achelctl repoList. See dodUpdaterAddRepo.
#
# Examples:
#   Build the DevOpsDreamUpdater
#   $0
#   
#   Build the DevOpsDreamUpdater and add repo extraRepo as iss dodUpdaterAddRepo had been called. This is purely for convenience.
#   $0 extraRepo



requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh

. $libDir/dodUpdater.sh

# Do the build.
dodBuild

# Add a repo if we've been given one.
if [ "$1" != '' ]; then
	dodAddRepo $1
fi
