#!/bin/bash
# Adds an achel repository. This is useful for adding your own achel import functionality.
# Syntax
#   addRepository /path/to/repo

. libs/build.sh

docker run -it devopsdreamupdater su - devOpsDreamUpdater -c 'bash'

commitToImage